from __future__ import annotations

import json

import pytest

from cropguard.config import CONFIG_DIR, data_root, load_config


def test_extends_deep_merges_parent():
    cfg = load_config(CONFIG_DIR / "resnet50_baseline.yaml")

    # From the child
    assert cfg["experiment_name"] == "resnet50-baseline"
    assert cfg["model"]["name"] == "resnet50"
    assert cfg["train"]["epochs"] == 12
    # Inherited from base.yaml and NOT clobbered by the child's partial `train` block
    assert cfg["train"]["optimizer"] == "adamw"
    assert cfg["train"]["early_stopping_patience"] == 5
    assert cfg["data"]["image_size"] == 224
    assert "extends" not in cfg


def test_challenger_overrides_augmentation():
    cfg = load_config(CONFIG_DIR / "convnext_tiny.yaml")
    assert cfg["augmentation"] == "heavy"
    assert cfg["train"]["weight_decay"] == pytest.approx(5.0e-2)


def test_env_var_overrides_data_root(monkeypatch, tmp_path):
    monkeypatch.setenv("CROPGUARD_DATA_DIR", str(tmp_path))
    cfg = load_config(CONFIG_DIR / "base.yaml")
    assert data_root(cfg) == tmp_path.resolve()


def test_all_shipped_configs_load():
    for path in CONFIG_DIR.glob("*.yaml"):
        cfg = load_config(path)
        if path.name == "base.yaml":
            continue
        assert cfg["experiment_name"], f"{path.name} is missing experiment_name"
        assert cfg["model"]["name"], f"{path.name} is missing model.name"


def test_classes_json_matches_serving_contract():
    """classes.json is the single source of truth for label order; skip until data is split."""
    path = CONFIG_DIR / "classes.json"
    if not path.exists():
        pytest.skip("classes.json is generated by cropguard.data.split")
    with open(path, encoding="utf-8") as f:
        classes = json.load(f)
    assert isinstance(classes, list) and classes == sorted(classes)
    assert len(classes) == len(set(classes))
